### ISSUE TITLE
Conditional autorun and command to run manually

### ISSUE THREAD

**Issue by jan-potuznik** [wpify/scoper#1]
Hello,
we would like to use scoper alongside other packages, without running it every time we call composer install or composer update. It would be ideal to run it with a command that we would enter in the scripts section of composer.json. Is it currently possible to achieve this? Would it be possible to add an "autorun" option to the scoper settings and provide a manual command to run it?

**Comment by jan-potuznik** [comment]
I prepared the proposed changes and a pull request:
https://github.com/wpify/scoper/pull/2

Is it possible to merge these changes?

I also found a way to run the scoper using a short script:
[run-scoper.txt](https://github.com/wpify/scoper/files/13309880/run-scoper.txt)

**Comment by mejta** [comment]
It would be a great idea to create a `composer scoper` script, that would take any of the commands composer have, but over scoped dependencies. What do you think, would you willing to extend the scoper to achieve that? So the commands `composer scoper install`, `composer scoper update` would work.

**Comment by jan-potuznik-z** [comment]
This is the best way I managed to do it so far: https://github.com/wpify/scoper/pull/3 I'm not aware of possibility to add script to parent composer.json.

**Comment by jan-potuznik-z** [comment]
Hello, would it be possible to merge the prepared pull requests please? I am ready to address possible issues.

**Comment by jan-potuznik-z** [comment]
@mejta Can we count on merging the provided pull requests or does it need to be solved differently on our side? Or do you have any comments that just need to be addressed?

**Comment by mejta** [comment]
Merged, thank you!
