### ISSUE TITLE
tmp folder is created instead of "deps"

### ISSUE THREAD

**Issue by sovetski** [wpify/scoper#5]
Hi,

My `composer-deps.json` file content:

```
{
    "config": {
        "platform": {
            "php": "8.2.0"
        }
    },
    "require": {        
        "aws/aws-sdk-php": "^3.257"
    }
}
```
`composer.json`:

```
{
    "require": {        
        "wpify/scoper": "^3.2"
    },
    "config": {
        "platform": {
            "php": "8.2.0"
        },
        "allow-plugins": {
            "wpify/scoper": true
        }
    },
    "extra": {
        "wpify-scoper": {
            "prefix": "MyCustomPrefix",
            "folder": "deps",
            "autorun": true
        }
    }
}
```

When I do `composer install`, it creates `tmp-9qsd65dz6` hashed temporary folder instead of `deps`

**Comment by mejta** [comment]
The tmp-* folder is created during the scoping process. It stays in case an error occurs during this process. The package "aws/aws-sdk-php" is quite huge, so I can imagine that it fails on memory. When I tested that on composer.json and composer-deps.json, it went fine on my side. Please try to set the memory limit for PHP to, e.g., 1GB.

![Snímek obrazovky 2024-03-19 v 9 47 20](https://github.com/wpify/scoper/assets/498441/ed8b0a62-14d0-4109-8c64-53d08bf5a5c0)

**Comment by mejta** [comment]
Closing for no reaction
