### ISSUE TITLE
Composer dependencies not using correct PHP version

### ISSUE THREAD

**Issue by ragulka** [wpify/scoper#6]
I'm trying to make sure that any composer dependencies that get installed work with PHP 7.4 - for comptibility reasons. I have defined the platform (as well as php version) in both `composer.json` and `composer-deps.json`:

## composer.json
```
{
    "autoload": {
        "psr-4": {
            "MyPlugin\\": "src/"
        }
    },
    "require": {
        "php": "^7.4 || ^8.0"
    },
    "extra": {
        "wpify-scoper": {
            "prefix": "MyDeps",
            "folder": "deps",
            "globals": [
                "wordpress",
                "woocommerce"
            ],
            "expose-global-constants": true,
            "composerjson": "composer-deps.json",
            "composerlock": "composer-deps.lock",
            "autorun": true
        }
    },
    "require-dev": {
        "wpify/scoper": "*"
    },
    "scripts": {
        "wpify-scoper": "wpify-scoper"
    },
    "config": {
        "platform": {
            "php": "7.4"
        },
        "allow-plugins": {
            "wpify/scoper": true,
            "php-http/discovery": true
        }
    }
}
```

## composer-deps.json
```
{
    "config": {
        "platform": {
          "php": "7.4"
        }
    },
    "require": {
        "php": "^7.4 || ^8.0",
        "illuminate/support": "^8.83"
    }
}
```

However, after `composer update`, and trying to visit the site I get the composer platform check error:
```
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.4.33.
```

I would expect that dependencies should not require PHP `8.1` _if_ my platform is set to `7.4`. 

Is there a way to work around or fix this?

**Comment by ragulka** [comment]
The culprit here seems to be the fact that I was requiring wpify/scoper locally:

```json
    "require-dev": {
        "wpify/scoper": "*"
    },
```

I now tried removing it and `composer global require wpify/scoper` and the dependencies are installed using the correct version now.

FWIW, trying to use version 3.1.3 of wpify/scoper in require-dev did not work - it would still install dependencies that required PHP 8.1, even if was actually running PHP 7.4

**Comment by mejta** [comment]
Hi @ragulka , the scoper should be installed system-wise with `composer global require wpify/scoper`. If you have the latest PHP version on the system, it will install the latest version of WPify Scoper. If you want to use a certain version of PHP for the project, please add that version to your `composer.json` and `composer-deps.json` files:

```json
{
  ...
  "config": {
    ...
    "platform": {
      "php": "7.4"
    }
  }
}
```

With this config, you can be sure that you are getting the correct version of dependencies for your project.

Version 3.1.x is outdated and should not be used on any project.
