### ISSUE TITLE
Configure php-scoper "exclude-files" not working

### ISSUE THREAD

**Issue by ManuDoni** [wpify/scoper#7]
Hello,
I really like this tool, but I'm having an issue.
I was not able to make the php-scoper config "exclude-files" work, passing a path that points to a file that is in the `deps` directory.
Maybe because I have to set the file path, pointing to the `tmp*` folder created at runtime, while scoping?

**Comment by mejta** [comment]
@ManuDoni  Please test that with 3.2.18 if the problem persists.

**Comment by ManuDoni** [comment]
Hello @mejta, I'm sorry, but I no longer work for the company where I used this tool.
At the time, I used a workaround.
Thank you anyway for the fix
