### ISSUE TITLE
Shouldn't wordpress/woocommerce symbols be excluded rather than exposed?

### ISSUE THREAD

**Issue by ragulka** [wpify/scoper#9]
As I was working on [this PR](https://github.com/wpify/scoper/pull/8), I noticed that after exposing WP/WC functions and symbols, they were prefixed in my composer dependencies.

It seems to me that wordpress and woocommerce functions, classes, etc, should not be exposed, but excluded, instead. The purpose of exposing functions seems to be that if the project (plugin) defines global functions, etc - that those should be left untouched/unprefixed. However, this setting does not affect composer dependencies. 

When I changed `expose-functions` to `exclude-functions` inside `wordpress.php`, and then re-ran scoper, these functions were now properly excluded from being prefixed (both in plugin and composer dependencies)

**Comment by mejta** [comment]
Merged, the new version will be released soon
